# Get the box up and running. These tasks run before the box is configured
# or the project is cloned or built. All system dependencies should be
# installed here.

- name: ensure base path exists and belongs to www-data
  file:
    path: "{{base_path }}"
    state: directory
    group: www-data
    owner: www-data
    recurse: yes

- name: Update apt/aptitude
  apt:
    name: aptitude
    state: latest

- name: ensure apt cache is updated
  apt: update_cache=yes cache_valid_time=3600

- name: ensure all packages are upgraded safely
  apt: upgrade=safe
  when: env != "development"

- name: add keys to apt
  apt_key: url={{item}} state=present
  with_items: "{{ apt_keys }}"

- name: add repos to apt
  apt_repository:
    repo: "{{item}}"
    state: present
  with_items: "{{ apt_repos }}"

- name: install apt packages
  apt:
    name: "{{item}}"
    state: latest
  with_items: "{{ apt_packages }}"

- name: install pip2 packages
  pip:
    name: "{{item}}"
    state: latest
  with_items: "{{ pip2_packages }}"

- name: install pip3 packages
  pip:
    name: "{{item}}"
    state: latest
    executable: pip3
  with_items: "{{ pip3_packages }}"
