#!/bin/sh
apt-get update
apt install libssl-dev -y
apt install python3 -y
apt install python3-dev -y
apt install python3-pip -y
apt install unattended-upgrades -y
pip3 install --upgrade pip
pip3 install ansible
pip3 install virtualenv
echo 'APT::Periodic::Update-Package-Lists "1";\nAPT::Periodic::Download-Upgradeable-Packages "1";\nAPT::Periodic::AutocleanInterval "7";\nAPT::Periodic::Unattended-Upgrade "1";' > /etc/apt/apt.conf.d/10periodic
cd /home/wptdash/wptdash/ansible
ansible-playbook provision.yml --vault-password-file ~/.vault_pass.txt
