- name: Install UWSGI
  pip:
    name: uWSGI
    state: present

- name: Remove existing uwsgi socket
  file:
    path: /tmp/prbuildbot.sock
    state: absent

- name: Create /etc/uwsgi
  file:
    path: /etc/uwsgi/vassals
    state: directory

- name: uwsgi.ini is loaded
  template:
    src: wptdash_uwsgi.ini.j2
    dest: /etc/uwsgi/vassals/wptdash_uwsgi.ini
    backup: no

- name: emperor.ini is loaded
  template:
    src: emperor.ini.j2
    dest: /etc/uwsgi/emperor.ini

- name: Emperor service is loaded
  template:
    src: emperor.uwsgi.service.j2
    dest: /etc/systemd/system/emperor.uwsgi.service
    backup: no

- name: Start uwsgi-emperor
  systemd:
    name: emperor.uwsgi
    daemon_reload: yes
    enabled: yes
    state: restarted
